with open('src/components/ContentPlanner.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

modal_html = """      </div>

      {/* Video Generation Modal */}
      {isGeneratingVideo && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 backdrop-blur-sm p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 w-full max-w-2xl shadow-2xl flex flex-col items-center justify-center min-h-[400px] relative overflow-hidden">
            
            <button 
              onClick={() => setIsGeneratingVideo(false)}
              className="absolute top-4 right-4 text-slate-500 hover:text-white z-10"
            >
              ✕
            </button>

            {!generationComplete ? (
              <div className="flex flex-col items-center justify-center text-center z-10">
                <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-6"></div>
                <h3 className="text-lg font-bold text-slate-200 mb-2">正在通过云端大模型渲染视频</h3>
                <p 
                  onClick={() => setGenerationComplete(true)} 
                  className="text-xs text-indigo-400 font-mono cursor-pointer hover:text-indigo-300 transition-colors"
                  title="点击文字可跳过等待"
                >
                  {generationMsg}
                </p>
                <div className="w-64 h-1.5 bg-slate-800 rounded-full mt-6 overflow-hidden relative">
                  <div className="absolute top-0 bottom-0 left-0 bg-indigo-500 animate-[pulse_2s_ease-in-out_infinite] rounded-full" style={{ width: '60%' }}></div>
                </div>
                <p className="text-[10px] text-slate-500 mt-4 max-w-xs">
                  预计渲染时间: 约 3 分钟。您可以将其放入后台运行。
                </p>
                <div className="absolute -bottom-20 -right-20 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl"></div>
                <div className="absolute -top-20 -left-20 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl"></div>
              </div>
            ) : (
              <div className="w-full flex flex-col items-center z-10 animate-fade-in">
                <h3 className="text-sm font-bold text-emerald-400 mb-4 flex items-center gap-2">
                  <span className="w-5 h-5 rounded-full bg-emerald-500 text-black flex items-center justify-center text-xs font-bold">✓</span> 视频生成完毕
                </h3>
                <div className="relative w-full max-w-sm rounded-xl overflow-hidden shadow-2xl border-2 border-slate-800 bg-black aspect-[9/16]">
                  <video 
                    src="/tk2.mp4" 
                    controls 
                    autoPlay 
                    loop
                    className="w-full h-full object-cover"
                  ></video>
                </div>
                <button 
                  onClick={() => {
                    setIsGeneratingVideo(false);
                    onAddRecreatedVideo({
                      id: 'V-REP-' + Math.floor(Math.random() * 1000),
                      title: 'Matcha Latte Aesthetic Vlog (Replicated)',
                      duration: 15,
                      tags: ['#matcha', '#aesthetic'],
                      niche: device.niche,
                      script: analysisReport?.recreateBlueprint?.captionSuggest || '',
                      thumbnailColor: 'bg-indigo-900',
                      tagline: 'Generated by PixVerse V6'
                    });
                    alert('已自动将视频保存至人设资源库！');
                  }}
                  className="mt-6 px-6 py-2.5 bg-emerald-500 hover:bg-emerald-600 text-black font-bold text-xs rounded-xl shadow-lg shadow-emerald-500/20 cursor-pointer transition active:scale-95 flex items-center gap-2"
                >
                  收录该视频至资源库
                </button>
              </div>
            )}
            
          </div>
        </div>
      )}

    </div>
  );
}"""

content = content.replace('      </div>\n\n    </div>\n  );\n}', modal_html)

with open('src/components/ContentPlanner.tsx', 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')
