import { Device, Persona, WarmupPlan, VideoAsset, DailyPlan, CreatorStats } from './types';

export const NICHES = [
  { id: 'aesthetic-cooking', label: '美食 ASMR / Aesthetic Cooking', description: 'ASMR 风格烹饪、精致摆盘、咖啡拉花、美学厨房', tag: '#aestheticcooking #asmrcooking' },
  { id: 'fitness', label: '健身运动 / Fitness & Wellness', description: '健身房打卡、高效训练、身心活力、减脂餐制作', tag: '#fitnessgoals #workoutmotivation' },
  { id: 'streetwear', label: '街头穿搭 / Streetwear Fashion', description: 'OOTD 穿搭、小众潮流鞋履、欧美高街与复古美学', tag: '#streetwear #ootdinspo' },
  { id: 'tech-gadgets', label: '数码科技 / Tech & Gadgets', description: '科技新品开箱、极简桌面搭建、AI 工具、未来生活方式', tag: '#techunboxing #desksetup' },
  { id: 'luxury', label: '奢华生活 / Luxury Lifestyle', description: '豪车超跑、奢侈单品开箱、五星级酒店旅行体验、精英日常', tag: '#luxurylifestyle #billionairelife' },


];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'device-1',
    name: 'iPhone 8 Plus #01',
    ip: '192.241.130.42',
    region: '美国纽约 (US-NY-Residential)',
    platform: 'TikTok',
    username: 'emma_kitchen_diaries',
    avatarColor: 'from-amber-400 to-orange-500',
    status: 'idle',
    niche: 'aesthetic-cooking',
    followerCount: 2430,
    videoCount: 12,
    totalViews: 45800,
  },
  {
    id: 'device-2',
    name: 'iPhone 8 #02',
    ip: '198.51.100.175',
    region: '美国洛杉矶 (US-LA-Residential)',
    platform: 'TikTok',
    username: 'fit_goddess_o',
    avatarColor: 'from-blue-400 to-indigo-500',
    status: 'warmup',
    niche: 'fitness',
    followerCount: 15800,
    videoCount: 28,
    totalViews: 324100,
  },
  {
    id: 'device-3',
    name: 'iPhone 8 Plus #03',
    ip: '64.233.160.78',
    region: '美国迈阿密 (US-MIA-Residential)',
    platform: 'Instagram',
    username: 'streetwear_kai',
    avatarColor: 'from-red-400 to-pink-500',
    status: 'idle',
    niche: 'streetwear',
    followerCount: 340,
    videoCount: 3,
    totalViews: 1250,
  },
  {
    id: 'device-4',
    name: 'iPhone 8 #04',
    ip: '104.244.42.1',
    region: '中国香港代理 (HK-Mobile-Static)',
    platform: 'YouTube',
    username: 'tech_unboxed_vibe',
    avatarColor: 'from-emerald-400 to-teal-500',
    status: 'posting',
    niche: 'tech-gadgets',
    followerCount: 8900,
    videoCount: 19,
    totalViews: 90420,
  }, ,
  {
    id: 'device-5',
    name: 'iPhone XR #05',
    ip: '88.140.23.111',
    region: '英国伦敦 (UK-LDN-Residential)',
    platform: 'TikTok',
    username: 'beauty_guru_x',
    avatarColor: 'from-fuchsia-400 to-purple-500',
    status: 'idle',
    niche: 'luxury',
    followerCount: 54200,
    videoCount: 142,
    totalViews: 1042000,
  },
  {
    id: 'device-6',
    name: 'iPhone 11 #06',
    ip: '142.250.18.1',
    region: '加拿大温哥华 (CA-VAN-Residential)',
    platform: 'Instagram',
    username: 'nature_vibe_ca',
    avatarColor: 'from-green-400 to-emerald-500',
    status: 'warmup',
    niche: 'aesthetic-cooking',
    followerCount: 120,
    videoCount: 2,
    totalViews: 850,
  },
  {
    id: 'device-7',
    name: 'iPhone 8 Plus #07',
    ip: '203.0.113.45',
    region: '澳大利亚悉尼 (AU-SYD-Mobile)',
    platform: 'YouTube',
    username: 'tech_aussie_mate',
    avatarColor: 'from-sky-400 to-blue-500',
    status: 'posting',
    niche: 'tech-gadgets',
    followerCount: 14500,
    videoCount: 45,
    totalViews: 890000,
  },
  {
    id: 'device-8',
    name: 'iPhone SE #08',
    ip: '45.22.12.89',
    region: '美国芝加哥 (US-CHI-Residential)',
    platform: 'TikTok',
    username: 'gym_bro_chi',
    avatarColor: 'from-red-500 to-orange-500',
    status: 'idle',
    niche: 'fitness',
    followerCount: 890,
    videoCount: 15,
    totalViews: 12400,
  },
  {
    id: 'device-9',
    name: 'iPhone X #09',
    ip: '198.2.14.77',
    region: '美国西雅图 (US-SEA-Residential)',
    platform: 'Instagram',
    username: 'coffee_aesthetic',
    avatarColor: 'from-amber-600 to-yellow-500',
    status: 'offline',
    niche: 'aesthetic-cooking',
    followerCount: 3200,
    videoCount: 30,
    totalViews: 45000,
  },
  {
    id: 'device-10',
    name: 'iPhone 12 #10',
    ip: '172.64.12.1',
    region: '新加坡机房 (SG-Cloud-Static)',
    platform: 'YouTube',
    username: 'crypto_daily_sg',
    avatarColor: 'from-indigo-500 to-purple-600',
    status: 'idle',
    niche: 'tech-gadgets',
    followerCount: 125000,
    videoCount: 205,
    totalViews: 5600000,
  },
  {
    id: 'device-11',
    name: 'iPhone 13 #11',
    ip: '172.64.187.29',
    region: '代理机房-集群节点 11',
    platform: 'YouTube',
    username: 'creator_011_official',
    avatarColor: 'from-emerald-400 to-teal-500',
    status: 'warmup',
    niche: 'streetwear',
    followerCount: 22540,
    videoCount: 443,
    totalViews: 1485784,
  },
  {
    id: 'device-12',
    name: 'iPhone 13 #12',
    ip: '172.64.163.102',
    region: '代理机房-集群节点 12',
    platform: 'TikTok',
    username: 'creator_012_official',
    avatarColor: 'from-yellow-400 to-orange-500',
    status: 'warmup',
    niche: 'tech-gadgets',
    followerCount: 89431,
    videoCount: 256,
    totalViews: 4235376,
  },
  {
    id: 'device-13',
    name: 'iPhone 13 #13',
    ip: '172.64.196.107',
    region: '代理机房-集群节点 13',
    platform: 'YouTube',
    username: 'creator_013_official',
    avatarColor: 'from-purple-500 to-indigo-600',
    status: 'posting',
    niche: 'fitness',
    followerCount: 70415,
    videoCount: 494,
    totalViews: 1222937,
  },
  {
    id: 'device-14',
    name: 'iPhone 13 #14',
    ip: '172.64.90.79',
    region: '代理机房-集群节点 14',
    platform: 'Instagram',
    username: 'creator_014_official',
    avatarColor: 'from-red-500 to-rose-600',
    status: 'offline',
    niche: 'aesthetic-cooking',
    followerCount: 62172,
    videoCount: 316,
    totalViews: 3671304,
  },
  {
    id: 'device-15',
    name: 'iPhone 13 #15',
    ip: '172.64.198.29',
    region: '代理机房-集群节点 15',
    platform: 'Instagram',
    username: 'creator_015_official',
    avatarColor: 'from-fuchsia-400 to-pink-500',
    status: 'posting',
    niche: 'luxury',
    followerCount: 75620,
    videoCount: 447,
    totalViews: 2880350,
  },
  {
    id: 'device-16',
    name: 'iPhone 13 #16',
    ip: '172.64.140.110',
    region: '代理机房-集群节点 16',
    platform: 'YouTube',
    username: 'creator_016_official',
    avatarColor: 'from-slate-400 to-slate-600',
    status: 'offline',
    niche: 'aesthetic-cooking',
    followerCount: 76548,
    videoCount: 395,
    totalViews: 3948316,
  },
  {
    id: 'device-17',
    name: 'iPhone 13 #17',
    ip: '172.64.137.215',
    region: '代理机房-集群节点 17',
    platform: 'TikTok',
    username: 'creator_017_official',
    avatarColor: 'from-red-500 to-rose-600',
    status: 'offline',
    niche: 'fitness',
    followerCount: 3664,
    videoCount: 61,
    totalViews: 4968747,
  },
  {
    id: 'device-18',
    name: 'iPhone 13 #18',
    ip: '172.64.95.43',
    region: '代理机房-集群节点 18',
    platform: 'Instagram',
    username: 'creator_018_official',
    avatarColor: 'from-cyan-400 to-blue-500',
    status: 'posting',
    niche: 'luxury',
    followerCount: 161730,
    videoCount: 81,
    totalViews: 2484262,
  },
  {
    id: 'device-19',
    name: 'iPhone 13 #19',
    ip: '172.64.32.13',
    region: '代理机房-集群节点 19',
    platform: 'Instagram',
    username: 'creator_019_official',
    avatarColor: 'from-purple-500 to-indigo-600',
    status: 'posting',
    niche: 'fitness',
    followerCount: 149515,
    videoCount: 200,
    totalViews: 1577953,
  },
  {
    id: 'device-20',
    name: 'iPhone 13 #20',
    ip: '172.64.157.125',
    region: '代理机房-集群节点 20',
    platform: 'YouTube',
    username: 'creator_020_official',
    avatarColor: 'from-cyan-400 to-blue-500',
    status: 'offline',
    niche: 'fitness',
    followerCount: 61846,
    videoCount: 136,
    totalViews: 4795972,
  },
  {
    id: 'device-21',
    name: 'iPhone 13 #21',
    ip: '172.64.39.55',
    region: '代理机房-集群节点 21',
    platform: 'YouTube',
    username: 'creator_021_official',
    avatarColor: 'from-cyan-400 to-blue-500',
    status: 'warmup',
    niche: 'aesthetic-cooking',
    followerCount: 135709,
    videoCount: 247,
    totalViews: 1123749,
  },
  {
    id: 'device-22',
    name: 'iPhone 13 #22',
    ip: '172.64.59.70',
    region: '代理机房-集群节点 22',
    platform: 'TikTok',
    username: 'creator_022_official',
    avatarColor: 'from-yellow-400 to-orange-500',
    status: 'warmup',
    niche: 'streetwear',
    followerCount: 162363,
    videoCount: 419,
    totalViews: 936349,
  },
  {
    id: 'device-23',
    name: 'iPhone 13 #23',
    ip: '172.64.184.214',
    region: '代理机房-集群节点 23',
    platform: 'Instagram',
    username: 'creator_023_official',
    avatarColor: 'from-cyan-400 to-blue-500',
    status: 'posting',
    niche: 'fitness',
    followerCount: 90259,
    videoCount: 157,
    totalViews: 4612681,
  },
  {
    id: 'device-24',
    name: 'iPhone 13 #24',
    ip: '172.64.78.165',
    region: '代理机房-集群节点 24',
    platform: 'TikTok',
    username: 'creator_024_official',
    avatarColor: 'from-purple-500 to-indigo-600',
    status: 'idle',
    niche: 'luxury',
    followerCount: 172122,
    videoCount: 206,
    totalViews: 1892574,
  },
  {
    id: 'device-25',
    name: 'iPhone 13 #25',
    ip: '172.64.24.246',
    region: '代理机房-集群节点 25',
    platform: 'YouTube',
    username: 'creator_025_official',
    avatarColor: 'from-fuchsia-400 to-pink-500',
    status: 'offline',
    niche: 'fitness',
    followerCount: 19572,
    videoCount: 48,
    totalViews: 3870248,
  },
];

export const INITIAL_PERSONAS: Record<string, Persona> = {
  'device-1': {
    id: 'device-1',
    avatarUrl: '/avatar (1).png',
    interests: ['Aesthetic Cooking', 'Family Recipes', 'Coffee ASMR', 'Home Baking', 'Kitchen Restock'],
    race: 'Caucasian (Western Housewives)',
    gender: 'Female',
    values: 'Family first, cozy home vibes, aesthetic culinary journey, warm and clean kitchen.',
    niche: 'aesthetic-cooking',
    bio: 'Mom of 2 | Sharing my daily kitchen routines, easy family recipes, and aesthetic coffee rituals. Making home feel like magic. ✨',
    tone: 'Warm, aesthetic, calming, ASMR-focused, family-oriented.',
  },
  'device-2': {
    id: 'device-2',
    avatarUrl: '/avatar (2).png',
    interests: ['HIIT Routines', 'Aesthetic Gym Outfits', 'Healthy Meal Prep', 'Gym Humor', 'Self-care Journaling'],
    race: 'Latina (拉丁裔偏好)',
    gender: 'Female',
    values: 'Body positivity, consistent discipline, high energy workout aesthetics, empowerment.',
    niche: 'fitness',
    bio: 'Your gym bestie. 🧘‍♀️ Sweat now, glow later. Daily wellness & high-impact aesthetics.',
    tone: 'Energetic, motivational, authentic, direct.',
  },
  'device-3': {
    id: 'device-3',
    avatarUrl: '/avatar (3).png',
    interests: ['Vintage Sneakers', 'OOTD Transition clips', 'Hip Hop Underground', 'Tokyo Street Culture'],
    race: 'African-American (非裔潮流偏好)',
    gender: 'Male',
    values: 'Originality, rebellion, thrift shop sustainability, raw city beats.',
    niche: 'streetwear',
    bio: 'Archiving street couture and rare sneakers. Vintage is the future.',
    tone: 'Chill, effortless, slang-casual, underground.',
  },
  'device-4': {
    id: 'device-4',
    avatarUrl: '/avatar (4).png',
    interests: ['Mechanical Keyboards', 'Desk Tour Reils', 'Indie Hacking', 'Futuristic Tech', 'Cyberpunk Aesthetics'],
    race: 'Caucasian (欧美极客偏好)',
    gender: 'Male',
    values: 'Productivity hacking, clean hardware configurations, minimalist future tech.',
    niche: 'tech-gadgets',
    bio: 'Unboxing the future. Clean setups & satisfying tech clicking sounds. Let\'s automate.',
    tone: 'Crisp, structured, high-tech, informational.',
  },
  'device-5': {
    id: 'device-5',
    avatarUrl: '/avatar (5).png',
    interests: ['Luxury Bags', 'Haute Couture', 'Jewelry', 'Paris Fashion Week', 'High-end Lifestyle'],
    race: 'Asian',
    gender: 'Female',
    values: 'Elegance, exclusivity, unapologetic luxury, confidence.',
    niche: 'luxury',
    bio: 'Curating the finest things in life. Paris / NYC / Tokyo. Living the dream.',
    tone: 'Sophisticated, exclusive, elegant, inspiring.',
  },
  'device-6': {
    id: 'device-6',
    avatarUrl: '/avatar (6).png',
    interests: ['Camping', 'Forest Aesthetics', 'Cabin Life', 'Outdoor Cooking', 'Nature Sounds'],
    race: 'Caucasian',
    gender: 'Female',
    values: 'Peace, nature connection, slow living, sustainability.',
    niche: 'aesthetic-cooking',
    bio: 'Finding peace in the wild. Cabin life and campfire recipes.',
    tone: 'Calm, grounded, peaceful, earthy.',
  },
  'device-7': {
    id: 'device-7',
    avatarUrl: '/avatar (7).png',
    interests: ['Smart Home Tech', 'PC Builds', 'Gaming Setups', 'Gadget Reviews', 'Tech Deals'],
    race: 'Caucasian',
    gender: 'Male',
    values: 'Innovation, efficiency, honest reviews, community.',
    niche: 'tech-gadgets',
    bio: 'Your honest tech mate from down under. Reviews, builds, and nerdy stuff.',
    tone: 'Friendly, enthusiastic, informative, casual.',
  },
  'device-8': {
    id: 'device-8',
    avatarUrl: '/avatar (8).png',
    interests: ['Powerlifting', 'Protein Recipes', 'Gym Vlogs', 'Motivation', 'Pre-workout'],
    race: 'Hispanic',
    gender: 'Male',
    values: 'Grind, discipline, brotherhood, pushing limits.',
    niche: 'fitness',
    bio: 'Lifting heavy and eating clean. Documenting the journey to 500lbs deadlift.',
    tone: 'Hype, motivational, raw, brotherhood.',
  },
  'device-9': {
    id: 'device-9',
    avatarUrl: '/avatar (9).png',
    interests: ['Latte Art', 'Coffee Roasting', 'Morning Routines', 'Cafe Hopping', 'Espresso Machines'],
    race: 'Asian',
    gender: 'Male',
    values: 'Craftsmanship, morning peace, aesthetic visuals, caffeine enthusiast.',
    niche: 'aesthetic-cooking',
    bio: 'Chasing the perfect pull. Daily coffee aesthetics and latte art.',
    tone: 'Smooth, relaxed, aesthetic, detail-oriented.',
  },
  'device-10': {
    id: 'device-10',
    avatarUrl: '/avatar (10).png',
    interests: ['Web3', 'Blockchain', 'Crypto Trading', 'Tech News', 'Investment'],
    race: 'Asian',
    gender: 'Male',
    values: 'Future of finance, decentralization, fast money, tech evolution.',
    niche: 'tech-gadgets',
    bio: 'Daily crypto & tech alpha from Singapore. Stay ahead of the curve.',
    tone: 'Fast-paced, analytical, sharp, confident.',
  },
};

export const DEFAULT_WARMUP_PLANS: WarmupPlan[] = [
  {
    day: 1,
    title: '第一天：细分领域探索与基础贴标',
    actions: [
      { type: 'search', param: 'Aesthetic Coffee Making', duration: 40 },
      { type: 'scroll', param: 'For You Page (Niche Relevant)', duration: 180 },
      { type: 'bookmark', param: 'High action rate cooking video', duration: 10 },
      { type: 'scroll', param: 'Competitor Feed', duration: 120 },
    ],
  },
  {
    day: 2,
    title: '第二天：互动习惯培养 (双击点赞流)',
    actions: [
      { type: 'scroll', param: 'For You Page', duration: 240 },
      { type: 'like', param: 'Like 3 target videos matching niche', duration: 15 },
      { type: 'profile', param: 'Visit creator account @asmr_baking', duration: 80 },
      { type: 'bookmark', param: 'Bookmark a 1M+ views video', duration: 10 },
    ],
  },
  {
    day: 3,
    title: '第三天：深度社交建立 (阅读与编写评论)',
    actions: [
      { type: 'search', param: 'Healthy breakfast preps', duration: 60 },
      { type: 'scroll', param: 'For You Page', duration: 300 },
      { type: 'comment', param: 'Genuine 5-word English comment matching scenario', duration: 30 },
      { type: 'share', param: 'Share video link via simulated DM clipboard', duration: 15 },
    ],
  },
  {
    day: 4,
    title: '第四天：垂类长视频驻留 (完播率拉升)',
    actions: [
      { type: 'scroll', param: 'Explore Tab / Searches', duration: 200 },
      { type: 'scroll', param: 'Watch full 2-min ASMR setup video', duration: 120 },
      { type: 'like', param: 'Double tap following user upload', duration: 10 },
    ],
  },
  {
    day: 5,
    title: '第五天：算法归类触发 (主动出击)',
    actions: [
      { type: 'search', param: 'Desktop build accessories', duration: 90 },
      { type: 'scroll', param: 'Interactive comment replying', duration: 150 },
      { type: 'bookmark', param: 'Collect 2 niche hashtag videos', duration: 20 },
    ],
  },
];

export const VIDEO_RESOURCES: VideoAsset[] = [
  {
    id: 'res-1',
    title: 'Easy Sunday Morning Pancakes 🥞✨',
    duration: 35,
    size: '15.2 MB',
    format: 'MP4',
    status: 'ready',
    thumbnailColor: 'bg-orange-900',
    tags: ['#pancakerecipe', '#sundaymorning', '#momlife', '#asmrcooking'],
    script: 'Sunday mornings are for fluffy pancakes and hot coffee. Here is my secret family recipe that never fails. Mix the dry ingredients, add vanilla extract...'
  },
  {
    id: 'res-2',
    title: 'Meal Prep: 5 Days of Healthy Lunches 🥗',
    duration: 45,
    size: '22.1 MB',
    format: 'MP4',
    status: 'ready',
    thumbnailColor: 'bg-emerald-900',
    tags: ['#mealprep', '#healthylunch', '#kitchenhacks', '#momhack'],
    script: 'Let us get ready for the week! Chopping veggies on Sunday saves me hours during busy weekdays. I love storing these in glass containers.'
  },
  {
    id: 'res-3',
    title: 'Aesthetic Coffee Pour Over ASMR ☕',
    duration: 25,
    size: '12.4 MB',
    format: 'MP4',
    status: 'processing',
    thumbnailColor: 'bg-amber-900',
    tags: ['#coffeeroutine', '#pourover', '#morningvibes', '#asmr'],
    script: '[Sound of beans grinding] The best part of my morning. Freshly ground beans, hot water, and 5 minutes of total silence before the kids wake up.'
  },
  {
    id: 'res-4',
    title: 'One-Pan Creamy Tuscan Chicken 🍗',
    duration: 55,
    size: '28.5 MB',
    format: 'MP4',
    status: 'ready',
    thumbnailColor: 'bg-red-900',
    tags: ['#onepandinner', '#familydinner', '#tuscanchicken', '#easyrecipe'],
    script: 'Busy weeknight? This one-pan Tuscan chicken takes only 20 minutes and tastes like a restaurant meal. Sun-dried tomatoes and spinach make the perfect sauce.'
  },
  {
    id: 'res-5',
    title: 'Baking Chocolate Chip Cookies with Kids 🍪',
    duration: 40,
    size: '18.9 MB',
    format: 'MP4',
    status: 'ready',
    thumbnailColor: 'bg-yellow-900',
    tags: ['#bakingwithkids', '#chocolatechip', '#baking', '#familytime'],
    script: 'Rainy days mean baking day! The secret to perfect chewy cookies is browning the butter first. Look at that dough!'
  },
  {
    id: 'res-6',
    title: 'Restocking My Kitchen Pantry ASMR 🥫',
    duration: 30,
    size: '16.7 MB',
    format: 'MP4',
    status: 'failed',
    thumbnailColor: 'bg-blue-900',
    tags: ['#restock', '#pantryorganization', '#asmrrestock', '#kitchengoals'],
    script: '[Tapping on glass jars] Time to refill the pasta and cereal. Organizing my pantry is my favorite kind of therapy.'
  }
];

export const MOCK_MONTHLY_PLANS: Record<string, DailyPlan[]> = {
  'aesthetic-cooking': [
    { day: 1, topic: 'Easy Sunday Morning Pancakes 🥞', direction: 'Fluffy pancakes, pouring syrup in slow motion, warm morning light.', scriptPrompt: 'Create a 15s aesthetic cooking video for Sunday morning pancakes.', suggestedTags: ['#pancakerecipe', '#sundaymorning'] },
    { day: 2, topic: 'Meal Prep: Healthy Lunches', direction: 'Chopping fresh vegetables, organizing glass containers.', scriptPrompt: 'ASMR vegetable chopping and aesthetic lunch prep.', suggestedTags: ['#mealprep', '#healthylunch'] },
    { day: 3, topic: 'Aesthetic Coffee Pour Over', direction: 'Close up of coffee dripping, steam rising, pouring hot water over ground beans.', scriptPrompt: 'Morning coffee routine ASMR with relaxing lo-fi background.', suggestedTags: ['#coffeeroutine', '#asmr'] },
    { day: 4, topic: 'One-Pan Creamy Tuscan Chicken', direction: 'Sizzling chicken, adding cream and spinach, rich colors.', scriptPrompt: 'Quick 20 minute family dinner recipe.', suggestedTags: ['#onepandinner', '#familydinner'] },
    { day: 5, topic: 'Baking Chocolate Chip Cookies', direction: 'Mixing dough, pulling apart a warm gooey cookie.', scriptPrompt: 'Baking cookies on a rainy afternoon with kids.', suggestedTags: ['#baking', '#chocolatechip'] },
    { day: 6, topic: 'Kitchen Pantry Restock ASMR', direction: 'Pouring dry goods into aesthetic glass jars, organizing.', scriptPrompt: 'Satisfying kitchen pantry restock ASMR.', suggestedTags: ['#restock', '#kitchengoals'] }
  ],
  'fitness': [
    { day: 1, topic: 'Ultimate Morning Core Routine', direction: 'High tempo sync beats, low-angle phone filming active leg holds.', scriptPrompt: 'Motivate viewers with intense 3 steps core exercises.', suggestedTags: ['#absroutine', '#morningworkout'] },
    { day: 2, topic: 'Gym Outfit Color Coordination', direction: 'Kick-off clothes transition, posing under clean neon gym lights showing fabric quality.', scriptPrompt: 'Showcase black/slate athletic fitness gear combo.', suggestedTags: ['#gymootd', '#fitgoddess'] },
    { day: 3, topic: 'Meal Prep: 40g Protein Garlic Chicken', direction: 'Flipping seasoned golden chicken breasts on grill pan, calorie text overlays.', scriptPrompt: 'Healthy recipes for high-protein lean bulking.', suggestedTags: ['#mealprep', '#highprotein'] },
    { day: 4, topic: 'Stretching Routine for Back Pain', direction: 'Serene yoga mat setup, focus on relaxing breathing circles.', scriptPrompt: '5 stretching positions for office posture correction.', suggestedTags: ['#backhealth', '#mindfulmovement'] },
    { day: 5, topic: 'Deadlift Form Hack: Lat Activation', direction: 'Red marker draw-overs, demonstrating scapula packing mistake vs proper pull.', scriptPrompt: 'Instructional guide to lift heavier without back injury.', suggestedTags: ['#deadlifthacks', '#weightlifting'] },
  ]
};

export const MOCK_CREATOR_STATS: Record<string, CreatorStats> = {
  'device-1': {
    dailyViews: [
      { date: '05/15', value: 1200 },
      { date: '05/16', value: 1800 },
      { date: '05/17', value: 4500 },
      { date: '05/18', value: 3900 },
      { date: '05/19', value: 8900 },
      { date: '05/20', value: 12500 },
      { date: '05/21', value: 13000 },
    ],
    dailyFollowers: [
      { date: '05/15', value: 8 },
      { date: '05/16', value: 12 },
      { date: '05/17', value: 45 },
      { date: '05/18', value: 32 },
      { date: '05/19', value: 121 },
      { date: '05/20', value: 240 },
      { date: '05/21', value: 290 },
    ],
    trafficSources: [
      { source: 'For You Page (推荐流量)', percentage: 89 },
      { source: 'Hashtag Search (标签检索)', percentage: 6 },
      { source: 'Personal Profile (个人主页)', percentage: 3 },
      { source: 'Followers Feed (粉丝关注)', percentage: 2 },
    ],
    topVideos: [
      { title: 'Ice Matcha Latte ASMR Float', views: 18400, likes: 2100, comments: 45, shares: 120, fypFraction: 0.94, retentionRate: 0.52 },
      { title: 'Custard Bun Steam Splitting Close', views: 8200, likes: 920, comments: 18, shares: 42, fypFraction: 0.88, retentionRate: 0.41 },
      { title: 'Pour Over Alchemy Filter Coffee', views: 5400, likes: 410, comments: 9, shares: 12, fypFraction: 0.82, retentionRate: 0.35 },
    ]
  },
  'device-2': {
    dailyViews: [
      { date: '05/15', value: 45000 },
      { date: '05/16', value: 52000 },
      { date: '05/17', value: 68000 },
      { date: '05/18', value: 71000 },
      { date: '05/19', value: 92000 },
      { date: '05/20', value: 110000 },
      { date: '05/21', value: 125000 },
    ],
    dailyFollowers: [
      { date: '05/15', value: 340 },
      { date: '05/16', value: 410 },
      { date: '05/17', value: 680 },
      { date: '05/18', value: 590 },
      { date: '05/19', value: 1200 },
      { date: '05/20', value: 1540 },
      { date: '05/21', value: 1980 },
    ],
    trafficSources: [
      { source: 'For You Page (推荐流量)', percentage: 92 },
      { source: 'Personal Profile (个人主页)', percentage: 4 },
      { source: 'Followers Feed (粉丝关注)', percentage: 3 },
      { source: 'Hashtag Search (标签检索)', percentage: 1 },
    ],
    topVideos: [
      { title: 'High-waist Gym Coordinate Transition', views: 142000, likes: 22400, comments: 195, shares: 1100, fypFraction: 0.96, retentionRate: 0.61 },
      { title: 'My 5:00 AM Routine: Stacking Gym Bricks', views: 98000, likes: 11800, comments: 112, shares: 740, fypFraction: 0.91, retentionRate: 0.54 },
      { title: 'Strict Glute Press Dumbbell Form Correction', views: 42000, likes: 3200, comments: 85, shares: 130, fypFraction: 0.84, retentionRate: 0.48 },
    ]
  }
};
